### ISSUE TITLE
GnuplotRB not working properly with Daru

### ISSUE THREAD

**Issue by lokeshh** [SciRuby/gnuplotrb#4]
I am having the following error with [this notebook](https://github.com/SciRuby/sciruby-notebooks/blob/master/Data%20Analysis/Time%20Series%20Functions.ipynb)

![image](http://i.imgur.com/D27C06y.png)

You can [click here](https://gist.github.com/lokeshh/9dbd4f0fd3f9a23801c1) for complete error message.

**Comment by dilcom** [comment]
Huh, seems very strange. As I can see from Daru sources, #keys is called on @relation_hash here https://github.com/v0dro/daru/blob/v0.1.2/lib/daru/index.rb#L122 which is initialized here https://github.com/v0dro/daru/blob/bf846e8340e81292a2bd313cb34f327f447d6225/lib/daru/index.rb#L57 .
@v0dro don't you have any thoughts, why it could be nil? As it seems for me, everything should be OK, if index is initialized properly.

**Comment by v0dro** [comment]
It's running fine on my computer!

I re-ran the entire notebook with daru 0.1.2 and gnuplotrb 0.3.0 and here's the cell that's giving you a problem:
![screenshot from 2016-03-22 15 09 06](https://cloud.githubusercontent.com/assets/2629909/13947431/8cde6e0e-f040-11e5-9eca-0147ee26aa40.png)

However then I ran the whole notebook with gnuplotrb `0.3.3` and daru `0.1.2` and it gave the error that @lokeshh  is talking about.

@dilcom I think the problem is that an update to daru in 0.1.2 has made it incompatible with that particular method in gnuplotrb.

**Comment by v0dro** [comment]
I think I found the problem. The method is:
``` ruby
    def get_daru_columns(data, cnt)
      new_opt = (2..cnt).to_a.join(':')
      if data.index.key(0).is_a?(DateTime) || data.index.key(0).is_a?(Numeric)
        "1:#{new_opt}"
      else
        "#{new_opt}:xtic(1)"
      end
    end
```

The problem might be that DateTimeIndex is no longer stored as a `relation_hash` and it does not contain a `key` method anymore. So it's reverting to the `Daru::Index#key` method since thats a super class of `DateTimeIndex`.

I'm just sending you a PR with a more flexible implementation that would not depend on future API changes.

**Comment by dilcom** [comment]
Great, thank you Sameer! My next question was "how to safely determine if index is a datetime", but you already solved it in pull request =). I'll release next minor version with this fix tomorrow.
